name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16.x']
    name: Node ${{ matrix.node }} sample
    steps:
      - name: Fetching base and head commit (pull_request)
        run: |
          git fetch --no-tags --prune --no-recurse-submodules --depth=$((${{ github.event.pull_request.commits }} + 1)) origin ${{ github.event.pull_request.head.sha }}
          git fetch --no-tags --prune --no-recurse-submodules --depth=10 origin ${{ github.event.pull_request.base.sha }}
          git checkout --progress --force ${{ github.event.pull_request.head.sha }}

          while [[ -n $(git rev-list shallow ^${{ github.event.pull_request.base.sha }}) ]]
          do
            git fetch --no-tags --prune --no-recurse-submodules --deepen=10 origin ${{ github.event.pull_request.base.sha }}
          done

          base=$(git rev-list ${{ github.event.pull_request.head.sha }} ^${{ github.event.pull_request.base.sha }} | tail --lines 1 | xargs -I {} git rev-parse {}~1)

          echo "BASE=$base" >> $GITHUB_ENV
          echo "HEAD=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: yarn

      - name: Run Eslint checks
        run: yarn check:es

      - name: Run Changed tests only
        run: npx jest --verbose --onlyChanged --changedSince=${{ github.event.workflow_run.head_sha }}
