name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16.x']
    name: Node ${{ matrix.node }} sample
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: |
          git fetch --no-tags --depth=1 origin master
          git checkout -b master
          git checkout ${{ github.event.pull_request.head.sha }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: yarn

      - name: Run Eslint checks
        run: yarn check:es

      - name: Run Changed tests
        run: yarn tests:changedsince
