name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Initializing git repository
        run: |
          git init --initial-branch=main
          git remote add origin ${{ github.event.repository.html_url }}

      - name: Fetching base and head commit (push)
        if: github.event_name == 'push'
        env:
          PUSHED_COMMITS: ${{ toJSON(github.event.commits) }}
        run: |
          if [[ ${{ github.event.before }} == 0000000000000000000000000000000000000000 ]]
          then
            before=$(echo "$PUSHED_COMMITS" | jq .[0].id --raw-output)

            git fetch --no-tags --prune --no-recurse-submodules --depth=2 origin $before ${{ github.event.after }}

            echo "BASE=$(git rev-parse $before~1)" >> $GITHUB_ENV
          else
            git fetch --no-tags --prune --no-recurse-submodules --depth=1 origin ${{ github.event.before }} ${{ github.event.after }}

            echo "BASE=${{ github.event.before }}" >> $GITHUB_ENV
          fi

          echo "HEAD=${{ github.event.after }}" >> $GITHUB_ENV

      - name: Fetching base and head commit (pull_request)
        if: github.event_name == 'pull_request'
        run: |
          git fetch --no-tags --prune --no-recurse-submodules --depth=$((${{ github.event.pull_request.commits }} + 1)) origin ${{ github.event.pull_request.head.sha }}
          git fetch --no-tags --prune --no-recurse-submodules --depth=10 origin ${{ github.event.pull_request.base.sha }}
          git checkout --progress --force ${{ github.event.pull_request.head.sha }}

          while [[ -n $(git rev-list shallow ^${{ github.event.pull_request.base.sha }}) ]]
          do
            git fetch --no-tags --prune --no-recurse-submodules --deepen=10 origin ${{ github.event.pull_request.base.sha }}
          done

          base=$(git rev-list ${{ github.event.pull_request.head.sha }} ^${{ github.event.pull_request.base.sha }} | tail --lines 1 | xargs -I {} git rev-parse {}~1)

          echo "BASE=$base" >> $GITHUB_ENV
          echo "HEAD=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn

      - name: Run Eslint checks
        run: yarn check:es

      - name: Run Changed tests only
        if: github.event_name == 'pull_request'
        run: npx jest --verbose --onlyChanged --changedSince=${{ env.BASE }}
